name: Deploy to Cloud Server

on:
  push:
    branches: [ "main" ]  # 只在 main 分支推送时触发

jobs:
  deploy:
    runs-on: ubuntu-latest  # 使用 GitHub 提供的 Linux 服务器

    steps:
      # 1. 拉取最新代码
      - uses: actions/checkout@v4

      # 2. 登录 Docker Hub（如果你的服务器从 Docker Hub 拉取镜像）
      - name: Login to Docker Hub
        if: github.ref == 'refs/heads/main'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 3. 通过 SSH 连接云服务器，并执行部署命令
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /path/to/your-project  # 进入你的项目目录（包含 docker-compose.yml）
            git pull origin main      # 拉取最新代码
            docker-compose pull       # 更新最新的 Docker 镜像
            docker-compose up -d      # 重新启动服务
