name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to Server
        env:
          PRIVATE_KEY: ${{ secrets.SSH_KEY }}
          SERVER_IP: ${{ secrets.SERVER_IP }}
          SERVER_USER: ${{ secrets.SERVER_USER }}
        run: |
          sudo apt-get update && sudo apt-get install -y ssh
          mkdir -p ~/.ssh/
          echo "$PRIVATE_KEY" > ~/.ssh/ForGithub.pem
          chmod 600 ~/.ssh/ForGithub.pem
          # 指定私钥登录
          ssh -i ~/.ssh/ForGithub.pem $SERVER_USER@$SERVER_IP << 'EOF'
            cd ~/Motion
            git pull origin master
            docker compose down
            docker compose up -d --build
          EOF
