name: 自动部署

on:
  push:
    branches:
      - main
    paths-ignore:
      - README.md
      - LICENSE

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: SSH 命令拉取代码
        uses: appleboy/ssh-action@main
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_KEY }}

          script: |
            # 进入项目目录
            cd ~/Motion

            # 确保 git 目录安全
            git config --global --add safe.directory ~/Motion

            # 拉取最新代码
            git pull origin main

            # 确保安装 docker-compose
            if ! command -v docker-compose &> /dev/null; then
              sudo curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
              sudo chmod +x /usr/local/bin/docker-compose
            fi

            # 使用 docker compose 进行部署
            if docker compose version > /dev/null 2>&1; then
              docker compose down
              docker compose up -d --build
            else
              sudo docker-compose down
              sudo docker-compose up -d --build
            fi
