name: 自动部署

on:
  push:
    branches:
      - main
    paths-ignore:
      - README.md
      - LICENSE


jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: SSH 命令拉取代码
        uses: appleboy/ssh-action@main
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_KEY }}

          script: |
            cd ~/Motion
            git pull origin main
            sudo docker compose down
            sudo docker compose up -d --build
